"""Convert dictionary tables into enums

Revision ID: 11fc23606c69
Revises: 4c6c2484039c
Create Date: 2026-06-27 21:46:31.449390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11fc23606c69'
down_revision: Union[str, Sequence[str], None] = '4c6c2484039c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    category_enum = sa.Enum('FOOD', 'JUNK', 'STUDIES', 'VACATION', 'TRANSPORTATION', 'HOUSING', 'HEALTH', 'LIESURE', 'BILLS', 'INVESTMENT', 'GIFTS', 'OTHER', name='category_enum')
    transaction_type_enum = sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='transaction_type_enum')
    op.drop_constraint(op.f('transactions_category_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_transaction_type_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_type_id'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_category_time'), table_name='transactions')
    op.drop_table('transaction_types')
    op.drop_table('categories')
    op.drop_column('transactions', 'category_id')
    op.drop_column('transactions', 'transaction_type_id')
    category_enum.create(op.get_bind(), checkfirst=True)
    transaction_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('transactions', sa.Column('category', category_enum, nullable=False))
    op.add_column('transactions', sa.Column('transaction_type', transaction_type_enum, nullable=False))
    op.create_index('idx_transactions_category_time', 'transactions', ['category', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_table('transaction_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('transaction_types_pkey'))
    )
    op.drop_index('idx_transactions_category_time', table_name='transactions')
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'category')
    sa.Enum(name='category_enum').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='transaction_type_enum').drop(op.get_bind(), checkfirst=True)
    op.add_column('transactions', sa.Column('transaction_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('idx_transactions_category_time'), 'transactions', ['category_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_transactions_type_id'), 'transactions', ['transaction_type_id'], unique=False)
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_foreign_key(op.f('transactions_transaction_type_id_fkey'), 'transactions', 'transaction_types', ['transaction_type_id'], ['id'])
    op.create_foreign_key(op.f('transactions_category_id_fkey'), 'transactions', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
