"""add 'is_canceled' column to 'transactions'

Revision ID: e1a128dd5d50
Revises: 11fc23606c69
Create Date: 2026-07-05 18:42:42.662956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a128dd5d50'
down_revision: Union[str, Sequence[str], None] = '11fc23606c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_canceled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_canceled')
    # ### end Alembic commands ###
