services:
  postgresql:
    container_name: acessoria-sql
    restart: unless-stopped
    image: postgres
    tty: true
    stdin_open: true
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts:/scripts
    ports:
      - '5432:5432'
    env_file:
      - .env